from home_page import HomePage
from cart_page import CartPage
from catalog_page import ProductCatalogPage
from checkout_page import CheckoutPage
from login_page import LoginPage


class Test_Web_Site:
    def test_displaying_links_and_buttons_on_the_home_page(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        assert home_page.is_catalog_menu_displayed()
        assert home_page.is_logo_displayed()
        assert home_page.is_search_button_displayed()
        assert home_page.is_search_field_displayed()
        assert home_page.is_cart_button_displayed()
        assert home_page.is_link_account_displayed()
        assert home_page.is_link_to_ask_a_question_displayed

    def test_all_elements_products_catalog_is_clickable(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.check_catalog_elements_is_clicable()

    def test_cart_page_is_empty(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        assert cart_page.cart_is_empty() is True

    def test_cart_page_is_not_empty(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_product1()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        assert cart_page.cart_is_empty() is False

    def test_search_result_matches_the_given_search_product(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.search_and_match_products()

    def test_add_to_cart_select_products(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        assert cart_page.cart_is_empty() is True
        cart_page.go_from_cart_to_catalog()
        catalog_page.add_to_cart_select_products()
        catalog_page.go_to_cart()
        assert cart_page.cart_is_empty() is False

    def test_checking_items_params_in_the_cart(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_products()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.contains_cart_product_affter_add()

    def test_total_amount_corresponds(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_products()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.contains_cart_product_affter_add()
        cart_page.the_total_amount_corresponds()

    def test_checking_add_quantity_in_the_cart(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_product1()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.add_quantity()
        cart_page.change_quantity_add_product_in_cart()

    def test_checking_minus_quantity_in_the_cart(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_product1()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.add_quantity()
        cart_page.reduce_the_amount_of()

    def test_remove_product_from_the_cart(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_product1()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.remove_product_from_cart()
        cart_page.cart_is_empty()

    def test_go_from_cart_to_home_page(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_products()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.go_from_cart_to_home()
        home_page.open()
        home_page.page_is_loaded()

    def test_go_from_cart_to_catalog_page(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_products()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.go_from_cart_to_catalog()
        catalog_page.page_is_loaded()

    def test_go_from_cart_to_order_form_page(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_products()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.go_to_order_form_page()
        checkout_page = CheckoutPage(browser)
        checkout_page.page_is_loaded()

    def test_max_price_slider(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.setting_price_parameters()

    def test_attempt_to_authorize_an_unregistered_user(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.input_password()
        login_page.click_element_robot()
        login_page.click_button_came_in()  # TODO: need breakpoint to fill captcha
        login_page.email_is_empty()

    def test_date_entry_no_unregistered_user(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.input_email_password_unregistered_user()
        login_page.click_element_robot()
        login_page.click_button_came_in()  # TODO: need breakpoint to fill captcha
        login_page.message_about_invalid_input()

    def test_registered_user_authorization(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.entering_data_of_a_registered_user()
        login_page.click_element_robot()
        login_page.click_button_came_in()  # TODO: need breakpoint to fill captcha
        login_page.click_button_cabinet_user()
        login_page.user_cabinet_is_excepted()

    def test_entering_an_incorrect_registered_user_password(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.entering_an_incorrect_registered_user_password()
        login_page.click_element_robot()
        login_page.click_button_came_in()  # TODO: need breakpoint to fill captcha
        login_page.message_about_invalid_input()

    def test_entering_password_entry_less_than_three_characters(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.click_button_register()
        login_page.user_registration_password_entry_less_than_three_characters()

    def test_entering_registered_user_if_field_name_empty(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.click_button_register()
        login_page. user_registration_without_filling_name()

    def test_entering_registered_user_if_field_email_empty(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.click_button_register()
        login_page.user_registration_without_filling_email()

    def test_entering_registered_user_if_field_email_not_correct(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.click_button_register()
        login_page.user_registration_filling_email_is_not_correct()

    def test_entering_registered_user_if_field_phone_empty(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.click_button_register()
        login_page.user_registration_without_filling_phone()

    def test_entering_registered_user_password_confirmation_is_not_correct(self, browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.click_button_register()
        login_page.user_registration_password_confirmation_is_not_correct()

    def test_attempt_to_register_a_user_with_an_already_registered_email(self,browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.click_button_register()
        login_page.user_registration_is_email_already_busy()

    def test_registration_new_user(self,browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.go_to_account()
        login_page = LoginPage(browser)
        login_page.page_is_loaded()
        login_page.click_button_register()
        login_page.date_input_user_registration()
        login_page.click_element_robot_registration()
        login_page.click_register()  # TODO: need breakpoint to fill captcha
        login_page.click_button_cabinet_user()
        login_page.user_cabinet_is_excepted()

    def test_checkout_unregistered_user(self,browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_product1()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.go_to_order_form_page()
        checkout_page = CheckoutPage(browser)
        checkout_page.page_is_loaded()
        checkout_page.date_input_user_unregistrated()

    def test_attempt_to_place_an_order_without_filling_in_the_name(self,browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_product1()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.go_to_order_form_page()
        checkout_page = CheckoutPage(browser)
        checkout_page.page_is_loaded()
        checkout_page.attempt_to_place_an_order_without_filling_in_the_name()

    def test_attempt_to_place_an_order_without_filling_in_the_email(self,browser):
        home_page = HomePage(browser)
        home_page.open()
        home_page.page_is_loaded()
        home_page.is_catalog_menu_displayed()
        home_page.go_to_categories_menu()
        catalog_page = ProductCatalogPage(browser)
        catalog_page.open()
        catalog_page.page_is_loaded()
        catalog_page.add_to_cart_select_product1()
        catalog_page.go_to_cart()
        cart_page = CartPage(browser)
        cart_page.open()
        cart_page.page_is_loaded()
        cart_page.go_to_order_form_page()
        checkout_page = CheckoutPage(browser)
        checkout_page.page_is_loaded()
        checkout_page.attempt_to_place_an_order_without_filling_in_the_name()


